### ISSUE TITLE
Not able to install it.

### ISSUE THREAD

**Issue by raibove** [shawnscoding/reactjs-crontab#9]
I am getting this error when I run 'npm i reactjs-crontab'. 
I guess this is error for reactjs version, is there any solution for it.
> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from reactjs-crontab@4.1.1
npm ERR! node_modules/reactjs-crontab
npm ERR!   reactjs-crontab@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by shawnscoding** [comment]
@raibove Hi. Thanks for the report.

I believe this issue has been solved after the update of the Reactjs version.
could you please try again?

I will close this issue but if the issue still occurs, please let me know.
